export const initialPatients = [
  {
    id: 1,
    name: "Gagan TP",
    age: 22,
    symptoms: "Allergic",
    appointmentDate: "26-10-2025",
    appointmentTime: "10:30",
    priority: "High",
  },
  {
    id: 2,
    name: "Srivathsa CM",
    age: 22,
    symptoms: "Fever",
    appointmentDate: "26-10-2025",
    appointmentTime: "09:00",
    priority: "Normal",
  },
];

export const styles = {
  dashboard: {
    fontFamily: '"Segoe UI", Tahoma, Geneva, Verdana, sans-serif',
    backgroundColor: "#a9d9f9ff",
    color: "#333",
  },
  header: {
    backgroundColor: "#62a6f0ff",
    color: "black",
    textwight: "thick",
    padding: "15px 25px",
    boxShadow: "0 2px 4px rgba(0, 0, 0, 0.1)",
  },
  mainContentWrapper: {
    padding: "20px",
  },
  content: {
    display: "flex",
    flexWrap: "wrap",
    gap: "20px",
  },
  footer: {
    backgroundColor: "#236ab0ff",
    color: "#000000ff",
    textwight: "bold",
    padding: "10px 20px",
    textAlign: "center",
    fontSize: "0.85em",
  },
  column: {
    flex: "1 1 300px",
    backgroundColor: "white",
    padding: "20px",
    borderRadius: "8px",
    boxShadow: "0 2px 4px rgba(64, 168, 203, 0.05)",
  },
  input: {
    width: "100%",
    padding: "10px",
    border: "1px solid #4e97e6ff",
    backgroundColor: " #a6caf1ff",
    borderRadius: "4px",
    boxSizing: "border-box",
  },
  button: {
    padding: "10px 15px",
    marginRight: "10px",
    border: "outset",
    borderRadius: "4px",
    cursor: "pointer",
    fontWeight: "bold",
  },
  primaryButton: {
    backgroundColor: "#4332d6ff",
    color: "white",
    borderRadius: "8px",
    border: "outset",
  },
  dangerButton: {
    backgroundColor: "#dc3545",
    color: "white",
    border: "outset",
    marginLeft: "5px",
  },
  table: {
    width: "100%",
    borderCollapse: "collapse",
    marginTop: "15px",
  },
  th: {
    backgroundColor: "#bcdeffff",
    padding: "12px",
    textAlign: "left",
    borderBottom: "2px solid #aadff2ff",
    cursor: "pointer",
  },
  td: {
    padding: "12px",
    borderBottom: "1px solid #eee",
  },
  priorityHigh: {
    color: "white",
    backgroundColor: "#dc3545",
    padding: "3px 8px",
    borderRadius: "12px",
    fontSize: "0.8em",
  },
  priorityNormal: {
    color: "white",
    backgroundColor: "#83f27dff",
    padding: "3px 8px",
    borderRadius: "12px",
    fontSize: "0.8em",
  },
  statCard: {
    flex: 1,
    padding: "15px",
    marginRight: "10px",
    backgroundColor: "#e6f7ff",
    borderRadius: "6px",
    borderLeft: "4px solid #007bff",
  },
};
